from .env_var_get import NODE_CLASS_MAPPINGS as ENV_NODE_CLASS_MAPPINGS
from .env_var_get import NODE_DISPLAY_NAME_MAPPINGS as ENV_NODE_DISPLAY_NAME_MAPPINGS
from .google_gemini import NODE_CLASS_MAPPINGS as GOOGLE_NODE_CLASS_MAPPINGS
from .google_gemini import NODE_DISPLAY_NAME_MAPPINGS as GOOGLE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **ENV_NODE_CLASS_MAPPINGS,
    **GOOGLE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ENV_NODE_DISPLAY_NAME_MAPPINGS,
    **GOOGLE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
